development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url:  redis://redistogo:b9b18e3300ef1878746a63a0b4b3bdc2@tarpon.redistogo.com:11990/
  channel_prefix: conference_app_production
